[package]
name = "easytime-internal-codegen"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
fs-err = "2"
ignore = "0.4"
prettyplease = "0.1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "visit-mut"] }
